### PR TITLE
Add back status module

### PR DESCRIPTION
**Pull request by TedTimbrell**

### CODE REVIEW

**Comment by TedTimbrell** [comment]
If this works, we should be in a position to switch over to heroku stack 18

**Comment by ericsandine** [comment]
yeah you can always test on staging, we may want to remove the buildpacks file from Cambly-Nginx right?

**Comment by TedTimbrell** [comment]
Yeah I'll push to staging first. And yeah removing that would be a good call, I'll put in a pr for that.

**Comment by garhiggins** [comment]
Are we planning to move this to heroku 18?

**Pull request merged**
